name: String3
markdown: redcarpet
highlighter: pygments
defaults:
  -
    scope:
      path: ""
    values:
      example1: "Cotton"
      example2: "Timber"
      example3: "Tantalum"
collections:
  why:
    output: false
  examples:
    output: true
  faqs:
    output: false
  materials:
    output: false
sass:
    sass_dir: _sass